[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/howardddwu/notebook/blob/master/Assignment%204%20-%20Judging%20Flowers.ipynb)

In [65]:
# Imports and pip installations (if needed)
import numpy as np
import pandas as pd
from sklearn import model_selection, metrics, svm, linear_model, datasets, neural_network, neighbors

# Part 1: Load the dataset

In [66]:
# Load the dataset (load remotely, not locally)
iris = datasets.load_iris()
# Output the first 15 rows of the data
listTarget_names = [f'{iris.target_names[0]}']*50 + [f'{iris.target_names[1]}']*50 + [f'{iris.target_names[2]}']*50

iris_data_frame = pd.DataFrame(data=np.c_[iris['data'],iris['target']],
                              columns=iris['feature_names']+['target'])
iris_data_frame.head(15)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   

    target  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
5      0.0  
6      0.0  
7      0.0  
8      0.0  
9      0.0  
10     0.0  
11     0.0  
12     0.0  
13     0.0  
14     0.0

In [67]:
# Display a summary of the table information (number of datapoints, etc.)
iris_data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    float64
dtypes: float64(5)
memory usage: 6.0 KB


In [68]:
iris_data_frame.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

# Part 2: Split the dataset into train and test

In [69]:
# Take the dataset and split it into our features (X) and label (y)
X = iris_data_frame[iris.feature_names]
y = iris_data_frame['target']



In [70]:
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = model_selection.train_test_split( X, y, train_size = 0.9, test_size = 0.1,
                                                                     shuffle = True, random_state = 6174)

# Part 3: Logistic Regression

In [71]:
# i. Use sklearn to train a LogisticRegression model on the training set
logistic_regression = linear_model.LogisticRegression(solver='lbfgs', max_iter=300)
logistic_regression.fit(X_train.values, y_train.values)



LogisticRegression(max_iter=300)

In [72]:
# ii. For a sample datapoint, predict the probabilities for each possible class
logistic_regression.predict(np.array([[5, 3, 1, 0]]))
logistic_regression.predict_proba(np.array([[5, 3, 1, 0]]))

array([[9.87254451e-01, 1.27455451e-02, 3.82708938e-09]])

In [73]:
# iii. Report on the score for Logistic regression model, what does the score measure?
logistic_regression.score(X_train.values, y_train.values)


0.9703703703703703

- The score measures the accuracy of the model on the given test data and labels.

In [74]:
# iv. Extract the coefficents and intercepts for the boundary line(s)
print('The coefficents for the Logistic Regression is: ', logistic_regression.coef_)
print('The intercepts for the Logistic Regression are: ',logistic_regression.intercept_)

The coefficents for the Logistic Regression is:  [[-0.39676549  0.90417794 -2.43728678 -1.08205138]
 [ 0.49734947 -0.28240878 -0.19264721 -0.88275555]
 [-0.10058398 -0.62176916  2.62993399  1.96480692]]
The intercepts for the Logistic Regression are:  [  9.61460702   2.10940681 -11.72401383]


# Part 4: Support Vector Machine

In [75]:
# i. Use sklearn to train a Support Vector Classifier on the training set
SVM = svm.SVC(kernel = 'linear',probability=True) 
SVM.fit(X_train.values, y_train.values)


SVC(kernel='linear', probability=True)

In [76]:
# ii. For a sample datapoint, predict the probabilities for each possible class
SVM_probabilities = pd.DataFrame(SVM.predict_proba(X_test), columns=iris['target_names'])
SVM_probabilities


C:\Users\Howar\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


setosa  versicolor  virginica
0   0.010408    0.057008   0.932584
1   0.003047    0.977887   0.019066
2   0.001158    0.000250   0.998592
3   0.006262    0.931761   0.061977
4   0.009041    0.045688   0.945271
5   0.021710    0.971013   0.007277
6   0.936211    0.046842   0.016947
7   0.002867    0.001277   0.995856
8   0.039294    0.949916   0.010790
9   0.916611    0.063744   0.019645
10  0.962199    0.026442   0.011360
11  0.006643    0.984504   0.008853
12  0.015811    0.978706   0.005483
13  0.053280    0.934457   0.012263
14  0.004428    0.002092   0.993480

In [77]:
# iii. Report on the score for the SVM, what does the score measure?
SVM.score(X_train.values, y_train.values)

0.9925925925925926

- The score measure the accuracy of the model on the given test data and labels.

# Part 5: Neural Network

In [78]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
MLP_Classifier = neural_network.MLPClassifier(solver='lbfgs', hidden_layer_sizes=(3, 3))
MLP_Classifier.fit(X_train, y_train.values.ravel())


C:\Users\Howar\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(hidden_layer_sizes=(3, 3), solver='lbfgs')

In [79]:
# ii. For a sample datapoint, predict the probabilities for each possible class
ML_Probalities = pd.DataFrame(MLP_Classifier.predict_proba(X_test), columns=iris['target_names'])
ML_Probalities


setosa    versicolor     virginica
0    7.868851e-89  4.253365e-03  9.957466e-01
1    6.215661e-53  9.999861e-01  1.385259e-05
2   1.850116e-121  6.973567e-09  1.000000e+00
3    2.795051e-58  9.998031e-01  1.968819e-04
4    1.295248e-96  1.777274e-04  9.998223e-01
5    1.022988e-43  9.999999e-01  1.427560e-07
6    9.999999e-01  5.016929e-08  1.101730e-25
7   6.875261e-120  1.324083e-08  1.000000e+00
8    2.019417e-42  9.999999e-01  7.504660e-08
9    9.999999e-01  5.016929e-08  1.101730e-25
10   9.999999e-01  5.016929e-08  1.101730e-25
11   5.870401e-49  9.999981e-01  1.925463e-06
12   3.606578e-40  1.000000e+00  2.453887e-08
13   6.701316e-31  1.000000e+00  2.463503e-10
14  4.771165e-114  1.438446e-07  9.999999e-01

In [80]:
# iii. Report on the score for the Neural Network, what does the score measure?
MLP_Classifier.score(X_test, y_test)


1.0

In [81]:
# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)


- After experimenting with several different options for the neural network, the highest confidence score that I was able to get was 98%.

# Part 6: K-Nearest Neighbors

In [82]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
KNN_Model = neighbors.KNeighborsClassifier(n_neighbors=3)
KNN_Model.fit(X_train, y_train.values.ravel())

KNeighborsClassifier(n_neighbors=3)

In [83]:
# ii. For a sample datapoint, predict the probabilities for each possible class
KNN_Probabilities = pd.DataFrame(KNN_Model.predict_proba(X_train), columns=iris['target_names'])
KNN_Probabilities


setosa  versicolor  virginica
0       0.0    1.000000   0.000000
1       1.0    0.000000   0.000000
2       0.0    1.000000   0.000000
3       0.0    1.000000   0.000000
4       1.0    0.000000   0.000000
..      ...         ...        ...
130     0.0    0.000000   1.000000
131     0.0    0.333333   0.666667
132     1.0    0.000000   0.000000
133     1.0    0.000000   0.000000
134     0.0    0.000000   1.000000

[135 rows x 3 columns]

In [84]:
# iii. Report on the score for kNN, what does the score measure?
KNN_Model.score(X_test, y_test)

1.0

- The score measure the accuracy of the model on the given test data and labels.

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

- The two models that performed the best on the dataset were the Neural Network Classifier and K-nearest Neighbors with a perfect score on 1.0 (for both training and test dataset). However, in predicting the probability the K-nearest Neighbors model was 100% certain about the correct answer on the test data set. 
- I believe this is because KNN is an example of a nonparametric model.